# Use root/example as user/password credentials
version: '3.1'
services:
    backend:
        image: backend
        restart: always
        ports:
            - 3000:3000
            - 3001:3001
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        links:
            - mongo
        depends_on:
            - mongo
