// @flow
import palette from './palette';

export default {
    h1: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: 32,
        letterSpacing: '-0.24px',
        lineHeight: '40px',
        fontSmoothing: 'antialiased',
    },
    h2: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: 24,
        letterSpacing: '-0.24px',
        lineHeight: '32px',
        fontSmoothing: 'antialiased',
    },
    h3: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: 20,
        letterSpacing: '-0.2px',
        lineHeight: '28px',
        fontSmoothing: 'antialiased',
    },
    h4: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: '20px',
        letterSpacing: '-0.06px',
        lineHeight: '24px',
        fontSmoothing: 'antialiased',
    },
    h5: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: '16px',
        letterSpacing: '-0.05px',
        lineHeight: '20px',
        fontSmoothing: 'antialiased',
    },
    h6: {
        color: palette.text.primary,
        fontWeight: 500,
        fontSize: '16px',
        letterSpacing: '-0.05px',
        lineHeight: '20px',
        fontSmoothing: 'antialiased',
    },
    body1: {
        color: palette.text.primary,
        fontSize: 14,
        letterSpacing: 'normal',
        lineHeight: 1.3,
        fontSmoothing: 'antialiased',
    },
    body2: {
        color: palette.text.primary,
        fontSize: 12,
        letterSpacing: '-0.05px',
        lineHeight: 1.2,
        fontSmoothing: 'antialiased',
    },
    subtitle1: {
        color: palette.text.secondary,
        fontWeight: 500,
        fontSize: 14,
        letterSpacing: '-0.05px',
        lineHeight: 1.3,
        fontSmoothing: 'antialiased',
    },
    subtitle2: {
        color: palette.text.secondary,
        fontWeight: 500,
        fontSize: 12,
        letterSpacing: '-0.05px',
        lineHeight: 1.2,
        fontSmoothing: 'antialiased',
    },
    button: {
        color: palette.text.primary,
        fontSize: 14,
        fontSmoothing: 'antialiased',
    },
    caption: {
        color: palette.text.primary,
        fontSize: 14,
        fontWeight: 600,
        letterSpacing: 'normal',
        lineHeight: 1.5,
        fontSmoothing: 'antialiased',
    },
    caption2: {
        color: palette.text.primary,
        fontSize: 12,
        fontWeight: 600,
        letterSpacing: '-0.05px',
        lineHeight: 1.3,
        fontSmoothing: 'antialiased',
    },
    overline: {
        color: palette.text.secondary,
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: '0.33px',
        lineHeight: 13,
        textTransform: 'uppercase',
        fontSmoothing: 'antialiased',
    },
};
