name: ci
on: [push]
jobs:
    code-style:
        name: Code Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install dependencies
              run: yarn
            - name: Prettier
              run: yarn prettier-check
    build-app:
        name: Build App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install dependencies
              working-directory: ./app
              run: yarn
            - name: Build
              working-directory: ./app
              run: yarn build
    build-rider-app:
        name: Build Rider App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install dependencies
              working-directory: ./rider-app
              run: yarn
            - name: Build
              working-directory: ./rider-app
              run: yarn build
